---

common: &common
  adapter: sqlite3
  database: shoes.db

development:
  <<: *common

test:
  <<: *common

production:
  adapter: postgresql
  host: ec2-107-20-179-213.compute-1.amazonaws.com
  database: dftf421lc10u2s
  username: qrkbxjxidxljed
  password: RwDNAUpVBviav9DdGKsz2pZySE